Repository LCStuber/Front-Maua-x-Fontys, pull requests merged in 2023-12, with the labels that each got.

#37 Feature: Microsoft Integration
  package-lock.json
  package.json
  src/App.jsx
  src/authConfig.js
  src/index.js
  src/pages/homepage/components/welcome.jsx
  src/pages/login/Login.jsx
  src/pages/login/components/loginContainer.jsx
  src/project-components/drawer.jsx
Labels: bug, enhancement

#38 BUG: Routes
  src/App.jsx
Labels: bug

#36 Information page
  package-lock.json
  public/index.html
  src/App.jsx
  src/imgs/logo-branco-print.png
  src/pages/college-info/collegeInfo.jsx
  src/pages/college-info/components/Card.jsx
  src/pages/college-info/components/row1.jsx
  src/pages/college-info/components/row2.jsx
  src/pages/college-info/components/row3.jsx
  src/pages/college-info/components/row4.jsx
  src/pages/college-info/components/row5.jsx
  src/pages/college-info/components/row6.jsx
  src/pages/college-info/components/row7.jsx
  src/pages/college-info/fonts/OFL.txt
  src/pages/college-info/fonts/Sansita-Black.ttf
  src/pages/college-info/fonts/Sansita-BlackItalic.ttf
  src/pages/college-info/fonts/Sansita-Bold.ttf
  src/pages/college-info/fonts/Sansita-BoldItalic.ttf
  src/pages/college-info/fonts/Sansita-ExtraBold.ttf
  src/pages/college-info/fonts/Sansita-ExtraBoldItalic.ttf
  src/pages/college-info/fonts/Sansita-Italic.ttf
  src/pages/college-info/fonts/Sansita-Regular.ttf
  src/pages/college-info/imgs/koifishu.svg
  src/pages/college-info/styled-components/Description.jsx
  src/pages/college-info/styled-components/Image.jsx
  src/pages/courses/components/courses_card.jsx
  src/pages/courses/components/courses_list.jsx
  src/pages/courses/components/modal.jsx
  src/pages/courses/courses.jsx
  src/pages/courses/imgs/compeng-img.jpg
  src/pages/courses/imgs/csi-img.jpg
  src/pages/courses/imgs/sys-img.jpg
  src/pages/homepage/components/navigation.jsx
  src/pages/homepage/components/welcome.jsx
  src/pages/homepage/imgs/default-image.jpg
  src/pages/stu-orgs/components/stuOrg_card.jsx
  src/pages/stu-orgs/components/stuOrgs_list.jsx
  src/pages/stu-orgs/imgs/DevCommunity.png
  src/project-components/drawer.jsx
  src/project-components/navbar.jsx
Labels: bug, enhancement

#39 Bugfix/images
  src/pages/college-info/components/row1.jsx
  src/pages/college-info/components/row2.jsx
  src/pages/college-info/components/row3.jsx
  src/pages/college-info/components/row4.jsx
  src/pages/college-info/components/row5.jsx
  src/pages/college-info/components/row6.jsx
  src/pages/college-info/components/row7.jsx
  src/pages/homepage/components/navigation.jsx
  src/pages/homepage/components/welcome.jsx
  src/project-components/navbar.jsx
Labels: bug

#40 Bug Fixes
  src/App.jsx
  src/pages/activityDetail/ActivityDetail.js
  src/pages/college-info/collegeInfo.jsx
  src/pages/college-info/fonts/OFL.txt
  src/pages/college-info/fonts/Sansita-Black.ttf
  src/pages/college-info/fonts/Sansita-BlackItalic.ttf
  src/pages/college-info/fonts/Sansita-Bold.ttf
  src/pages/college-info/fonts/Sansita-BoldItalic.ttf
  src/pages/college-info/fonts/Sansita-ExtraBold.ttf
  src/pages/college-info/fonts/Sansita-ExtraBoldItalic.ttf
  src/pages/college-info/fonts/Sansita-Italic.ttf
  src/pages/college-info/fonts/Sansita-Regular.ttf
  src/pages/college-info/styled-components/Description.jsx
  src/pages/courses/components/courses_card.jsx
  src/pages/courses/components/modal.jsx
  src/pages/homepage/components/welcome.jsx
  src/pages/login/components/loginContainer.jsx
  src/pages/login/imgs/logo-branco-print.png
  src/pages/login/imgs/microsoft-365-logo.png
Labels: bug

#33 Feature/announcement
  src/App.jsx
  src/pages/announcement/Announcement.css
  src/pages/announcement/Announcement.js
  src/pages/announcementstudent/StuAnnouncement.css
  src/pages/announcementstudent/StuAnnouncement.js
  src/project-components/drawer.jsx
Labels: enhancement

#41 mobile design fix login page
  src/pages/login/App.css
  src/pages/login/styled-components/Body.jsx
  src/pages/login/styled-components/clouds.jsx
  src/pages/login/styled-components/loginContainer.jsx
Labels: bug

#42 Bug reposivity fix
  src/pages/login/App.css
  src/pages/login/Login.jsx
  src/pages/login/styled-components/Body.jsx
  src/pages/login/styled-components/clouds.jsx
  src/pages/login/styled-components/loginContainer.jsx
Labels: bug

#34 add display route button
  src/pages/maua-location/MauaLocation.css
  src/pages/maua-location/MauaLocation.js
Labels: bug, enhancement

#54 Bugfix/interactive campus map
  package-lock.json
  package.json
  src/pages/interactiveMap/InteractiveMap.js
  src/pages/interactiveMap/components/ActivitiesMonitor.css
  src/pages/interactiveMap/components/ActivitiesMonitor.js
  src/pages/interactiveMap/components/AllActivitiesButton.css
  src/pages/interactiveMap/components/AllActivitiesButton.js
  src/pages/interactiveMap/components/GoogleMapComponent.css
  src/pages/interactiveMap/components/GoogleMapComponent.js
  src/pages/interactiveMap/components/SelectBlockButton.css
  src/pages/interactiveMap/components/SelectBlockButton.js
  src/pages/interactiveMap/components/coordinates.json
  src/pages/interactiveMap/components/unused/SeeMoreButton.css
  src/pages/interactiveMap/components/unused/SeeMoreButton.js
  src/pages/interactiveMap/imgs/plus_icon.svg
  src/project-components/drawer.jsx
Labels: bug

#56 fix
  src/pages/activities/Activities.js
  src/pages/college-info/components/Card.jsx
  src/pages/college-info/components/row7.jsx
  src/pages/interactiveMap/components/ActivitiesMonitor.js
Labels: bug

#57 BUG: Activities not showing
  src/pages/activities/Activities.js
  src/pages/interactiveMap/components/ActivitiesMonitor.css
  src/pages/interactiveMap/components/ActivitiesMonitor.js
Labels: bug
